### ISSUE TITLE
Number of project title on menu

### ISSUE THREAD

**Issue by nazamateo** [plantagoIT/strapi-drag-drop-content-type-plugin#13]
Is there already a feature on how to increase the number of projects on the menu? I can only reorder the first 10 projects ordered by rank.

**Comment by derschiw** [comment]
Hey thanks for your contribution. As far as I understand, this is a duplicate of #9, isn't it? :)

**Comment by derschiw** [comment]
I guess this is fixed with 310b5de98b1c21b89425a681c630cd5902e0743a
