### ISSUE TITLE
Page crashes after clicking show sort modal button

### ISSUE THREAD

**Issue by nazamateo** [plantagoIT/strapi-drag-drop-content-type-plugin#26]
I have an error in the console after the page loads, 
![image](https://user-images.githubusercontent.com/96044328/214282675-37504085-5ab1-4cec-bcf6-95df9f282738.png)

I checked the source and I think the error comes from this function
![image](https://user-images.githubusercontent.com/96044328/214284295-f9091456-cc4d-4fac-a3c4-e35e6aabb436.png)

I checked network responses but all responses are ok and status are 200
![image](https://user-images.githubusercontent.com/96044328/214283128-c96c091f-fdd4-4a41-8f10-682dd14939d5.png)

then after clicking the sort modal button, 
![image](https://user-images.githubusercontent.com/96044328/214282333-4af50760-e446-4d57-90e5-5c90c9e4e8cb.png)

The page crashes
![image](https://user-images.githubusercontent.com/96044328/214283501-dfe97ccf-a7f6-473a-9145-2f53a9851fad.png)

p.s.
plugin was working good before I updated the plugin yesterday. already checked the source code but still cant figure what causes the error. Your plugin is very helpful on our website. Thanks for your time always.

**Comment by zadinvit** [comment]
@derschiw Make hotfix fo #23 and there is still some error, but I am not able to find it. So maybe just use version 1.3.2. It will work if you using name rank for rank field. 

@nazamateo

**Comment by derschiw** [comment]
@nazamateo I can't reproduce it right now. 
- Does your model have a field named rank?
- have you have configured 'rank' in the settings?
- does it happen only on a full page reload?
- does it happen instantly when clicking on the sort modal button?

**Comment by derschiw** [comment]
i managed to fix this issues in 1.3.4
