### ISSUE TITLE
Problems in Strapi 4.6.0

### ISSUE THREAD

**Issue by exitsimulation** [plantagoIT/strapi-drag-drop-content-type-plugin#28]
After installation this plug-in is not showing up in my settings. I followed the installation guide and added this package to both dev and production `plugins.ts` (note I am using typescript).

It is however showing up under installed plug-ins which is strange.
![image](https://user-images.githubusercontent.com/13287154/217625991-ab3d457e-d1be-40ce-9089-102869b422e4.png)

**Comment by bespoke-dungnguyen** [comment]
I have same issue
    "@retikolo/drag-drop-cont
![2023-12-07 16 02 44](https://github.com/plantagoIT/strapi-drag-drop-content-type-plugin/assets/126946280/b0fddb72-ea65-4c5f-816d-5bcf651dfdab)
ent-types": "^1.5.0",
        "@strapi/strapi": "4.14.4",

**Comment by bespoke-dungnguyen** [comment]
I have same issue
<img width="824" alt="Screenshot 2023-12-07 at 9 59 27 PM" src="https://github.com/plantagoIT/strapi-drag-drop-content-type-plugin/assets/126946280/2d232f97-49fa-49ae-99c6-2f9ed8f7e455">
  "dependencies": {
    "@retikolo/drag-drop-content-types": "^1.5.0",
    "@strapi/plugin-i18n": "4.14.4",
    "@strapi/plugin-users-permissions": "4.14.4",
    "@strapi/strapi": "4.14.4",
    "better-sqlite3": "8.6.0",
    "pg": "^8.11.3",
    "strapi-provider-cloudflare-r2": "^0.2.4"
  },

**Comment by bespoke-dungnguyen** [comment]
Use yarn install instead pnpm it work. I don't know how @@
