### ISSUE TITLE
Live update the list view

### ISSUE THREAD

**Issue by derschiw** [plantagoIT/strapi-drag-drop-content-type-plugin#3]
After updating the ranks, the list view will stay the same (even when configured correctly). Somehow the page should be reloaded to update the correct positions. However a full page reload might not be the desired option. Find a way to solve this.

**Comment by jpizzle34** [comment]
Hi @derschiw,

Do you have time to review my pull request? Let me know if that solves the issue. Happy to discuss.

Thanks and Happy Holidays :smile:

**Comment by derschiw** [comment]
Hey @jpizzle34 
Thank you very much for your pull request: :tada:  Right now I'm at holidays, but I will take a look at it when I'm back next year! :)

**Comment by derschiw** [comment]
Fixed with #12
