### ISSUE TITLE
Enable plugin in Content-type Builder

### ISSUE THREAD

**Issue by wai15985** [plantagoIT/strapi-drag-drop-content-type-plugin#31]
Is it possible to add a checkbox in advance settings?
Cause strapi will throw exception when rank field not found.

**Comment by derschiw** [comment]
I think I fixed this error message in c45614dd186ea92933849ea5442faebf3e535ef2 :) Is this what you meant?

**Comment by derschiw** [comment]
I close this as the exception should not be thrown anymore, and the plugin should only work when adding a _rank_ field (which is "enabling" the plugin in a sense)
