### ISSUE TITLE
Is it possible to add new field along with title in drag drop menu

### ISSUE THREAD

**Issue by amjadniazi48** [plantagoIT/strapi-drag-drop-content-type-plugin#36]
The plugin shows only the title field. Can we increase the number of displayed fields along with the title like it can display the title, slug in drag drop menu

**Comment by SSDO-Pakistan** [comment]
Let's suppose you have products with categories, and you want to sort products category-wise, so you need title of the product with the category name.

**Comment by derschiw** [comment]
Ok I agree, this could be useful. I will consider implementing this when I find time to do so. (I think adding relation-field to title field however, is not possible yet anyways.)

**Comment by SSDO-Pakistan** [comment]
Another scenario without relation is if you have an enumeration field named "type" and you want to sort your records according to the type, then, in that case, it will be useful.

**Comment by derschiw** [comment]
Solved in 1.4.1 (see README.md for the guide).
