### ISSUE TITLE
Doesn't work with Strapi v4.4.1

### ISSUE THREAD

**Issue by kevinblanco** [plantagoIT/strapi-drag-drop-content-type-plugin#4]
After following the guide, the Order functionality is not working in Strapi v4.4.1, I do see the settings of the plugin, I see that a weird field name appears on the list called RABOO but there is no drag and drop or any sorting functionality.

**Comment by stattmal** [comment]
Same issue, I'm not able to drag & drop my collection entries.

**Comment by matasskarzauskas** [comment]
Having same issue, only RABOO field visible in field names.

**Comment by derschiw** [comment]
It tested it on Strapi v4.4.3 an it worked for me

Issues could be
1. There must be at least one entry in your collection. Is this the case?
2. Did you label the field names in your content-type correctly (case sensitive)?

The Raboo was a mistake indeed...

**Comment by stattmal** [comment]
Still not working at my installation with v4.3.8 and drag-drop-content-types v1.0.6. There is no button (with three lines) in the upper right menu, which will open a drag and droppable list.

## Configuration
![config](https://user-images.githubusercontent.com/66730739/195352177-ef0c3127-848f-48dc-8c6e-3df1529a345c.png)

## Content-Type
![content-type](https://user-images.githubusercontent.com/66730739/195352168-a4ccba9a-6b32-417e-abbe-8641ee54fdf1.png)

## View
![view](https://user-images.githubusercontent.com/66730739/195352172-9bdca857-b6e9-4c12-9f13-5462b1662e15.png)

**Comment by zadinvit** [comment]
Same for me. I tested it on 4.3.9 and 4.4.1 with version 1.0.4 and 1.0.6 and not working. It's seems that problem is in initializeContentType function. 

I try rewrite code and enable button and nothing happen after click on button.

**Comment by kahrpatrick** [comment]
I found a bug that prevented the sorting modal from fetching the settings. With the fix in #5 the plugin works for me.

**Comment by derschiw** [comment]
I merged and published #5. Hopefully this will solve the issue.

If not: please go to the browser console to see if there are any errors. This would be very useful debug information, since I cannot adress the issue properly otherwise. Thank you <3

**Comment by DylPayne** [comment]
Working now. Thank you!!!

**Comment by zadinvit** [comment]
Hi, now it's working. But drag and drop not working for me. But i create another issue for problem with drag and drop tool.

**Comment by DylPayne** [comment]
I experienced the same thing (using Chrome on Mac). When I use it in Safari it works 100%

**Comment by derschiw** [comment]
@zadinvit I created a new issue #6. Please provide some more information such as:

- Error logs from the browser console
- Strapi version number
- Used webbrowser (+ version)
- Everything else that could be useful

**Comment by derschiw** [comment]
Thanks to @zadinvit 's work, the plugin has now switched to a more broadly supported drag-and-drop library. Thanks very much for this contribution! I hope this will fix the issues.

It is now released under version 1.1.0 on npm.
