### ISSUE TITLE
reordering does not trigger webhooks

### ISSUE THREAD

**Issue by mindshaped** [plantagoIT/strapi-drag-drop-content-type-plugin#49]
Hi,
we're using strapi as headless cms, triggering deployments for static frontend generation. this works well with having the webhooks in strapi settings activated (on entry creation and entry update triggers).

when only reordering with the strapi-drag-drop-content-type-plugin panel, the webhooks are not getting fired though and it's necessary to go into (any) entry, edit it and save/update in order to fire the hook.

is it possible, to somehow trigger a "save" or "update" event on reordering, so the hooks are also fired then? 

thanks.

**Comment by derschiw** [comment]
It would be possible to write something in there `afterUpdate`method here:

https://github.com/plantagoIT/strapi-drag-drop-content-type-plugin/blob/staging/admin/src/components/SortModal/index.js#L170

However I'm not the best React programmer, so I don't know how to write these kind of hooks. Do you?

**Comment by mindshaped** [comment]
@derschiw interesting! I'm mostly familiar with vue instead of react, so it would take some time to get into this. for now I might fall back to displaying the order field in editing mode and let the customer save it (which triggers the hook), instead of using the drag&drop feature in the list overview.

**Comment by derschiw** [comment]
Fixed in #88
