### ISSUE TITLE
Order by components - content type

### ISSUE THREAD

**Issue by gianmachado** [plantagoIT/strapi-drag-drop-content-type-plugin#54]
Hello guys, i need help!!
I'm using version "**@retikolo/drag-drop-content-types": "^1.3.9"** and would like to know how I can order a content type by component? 

This is my structure:
![image](https://github.com/plantagoIT/strapi-drag-drop-content-type-plugin/assets/21374011/80aa42cc-b26a-4dae-83fa-fac19a3b5ef2)

In Drag Drop Content Type Config: 
Rank Field name: order 
Title Field Name: ????????????? (How I can use field content.title, like a screenshoot)

**Comment by derschiw** [comment]
I think that's currently not possible, and I'm not planning to implement this yet. Maybe you should create a dummy field for this purpose, update it in the lifecycles and hide it for the users.
