### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by derschiw** [plantagoIT/strapi-drag-drop-content-type-plugin#6]
Hi, now it's working. But drag and drop not working for me. But i create another issue for problem with drag and drop tool.

_Originally posted by @zadinvit in https://github.com/plantagoIT/strapi-drag-drop-content-type-plugin/issues/4#issuecomment-1277240726_

**Comment by zadinvit** [comment]
Hi, I working on library change. 

There is more info:
Dragging and drop not working on chrome (Version 105.0.5195.102 (Official Build) (arm64)) (It's very hard to click and get draging div, so it's working only in 10% of clicks). But after I open console for debug, it's start work very nice. 

On safari is working correctly. 

I think problem can be in DragSortableList component. It's old library.

Maybe change sort library to - https://github.com/clauderic/react-sortable-hoc can fix this. 

I tried rewrite it. But i don't have any experience with strapi UI. 

Right now i rewrite ui part, but there is diffrent update function. Can you look at it? 

https://github.com/zadinvit/strapi-drag-drop-content-type-plugin/blob/staging/admin/src/components/SortModal/index.js

I create fork and code is here. I need change setContentType to setData and only storing data from Strapi. But update function is little hard to read for me. 

Sorting is working with new library very good.

**Comment by zadinvit** [comment]
Thanks, we tested it on more PC, and it's not working on chrome. So i try rewrite it, but i don't know if I will have time this week. But I try do it. 

Thanks for comments for code. And yea i know i need rewrite whole update content, because there is diffrent logic here.

**Comment by zadinvit** [comment]
https://github.com/zadinvit/strapi-drag-drop-content-type-plugin/blob/staging/admin/src/components/SortModal/index.js

I made some changes, but I can't find solution how to debug this in strapi project. Console logs and breakpoints not working.  Can you check this and tell me how you debugging your code? Because it's seems that should work, but i think sort function is not triggered.

@derschiw

**Comment by derschiw** [comment]
Thanks to @zadinvit 's work, the plugin has now switched to a more broadly supported drag-and-drop library. Thanks very much for this contribution! I hope this will fix the issues.

It is now released under version 1.1.0 on npm.
