### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by ChinaeduO** [plantagoIT/strapi-drag-drop-content-type-plugin#7]
This plugin does not work with internationalization. It only sets the rank on the default language, but not on the translations.

**Comment by derschiw** [comment]
Thanks for your input. I will take a look at it next week, and see how I can fix it!

**Comment by captainkie** [comment]
hi, i have same issue. i use patch-package add another parameters to query like this

`
+	const queryString = window.location.search;
+	const urlParams = new URLSearchParams(queryString);
+	const pageSize = (urlParams.has('pageSize') ? urlParams.get('pageSize') : 100);
+	const locale = (urlParams.has('plugins[i18n][locale]') ? urlParams.get('plugins[i18n][locale]') : '');`

`const { data } = await axiosInstance.get(
-          `/content-manager/collection-types/${contentTypePath}?sort=rank:asc`
+          `/content-manager/collection-types/${contentTypePath}?pageSize=${pageSize}&sort=rank:asc&plugins[i18n][locale]=${locale}``

and enable localization for rank field

**Comment by derschiw** [comment]
The plugins works now with internationalization. Thanks @captainkie. For the pageSize I open a new ticket, since I'm not sure whether this is expected behavior.
