### ISSUE TITLE
Question: Show entry title on dropdown

### ISSUE THREAD

**Issue by blirag** [plantagoIT/strapi-drag-drop-content-type-plugin#71]
how do I show the title of my page in the sort menu? 

![image](https://github.com/plantagoIT/strapi-drag-drop-content-type-plugin/assets/52337462/e69c81a2-9553-4b90-8bca-f68b1a7ea824)

**Comment by derschiw** [comment]
Go to Settings -> Drag Drop Content Types -> Configuration and add the name of the field to be displayed under "Title Field Name"
