### ISSUE TITLE
Ability to hide configuration for not admin users?

### ISSUE THREAD

**Issue by pimpelsang** [plantagoIT/strapi-drag-drop-content-type-plugin#72]
I can't find "Drag Drop Plugin" under settings -> administrator panel Roles -> Plugins. I'd like to have it also configurable by role.

Here it's missing in plugins list although I have drag and drop plugin installed:
![image](https://github.com/plantagoIT/strapi-drag-drop-content-type-plugin/assets/1148362/c06aadae-3f66-4921-9076-b88e3d398fc5)

**Comment by derschiw** [comment]
Feel free to provide me more information on how to implement this or submit a PR and I will consider it! :)

**Comment by pimpelsang** [comment]
I think it's like that:
https://forum.strapi.io/t/limiting-access-of-a-custom-plugin-to-admin-users-only/27546

one example plugin
https://github.com/kucherenko/strapi-plugin-passwordless/blob/main/server/bootstrap.js#L70C9-L70C69

**Comment by ulysse-lacour** [comment]
Really willing to have this too!

**Comment by derschiw** [comment]
Added in version 1.6.0
