### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by Hvesyr** [plantagoIT/strapi-drag-drop-content-type-plugin#81]
Am I doing something wrong?

Using Strapi v4.20.0

My steps:

Installed with `npm install @retikolo/drag-drop-content-types`
Added the config to enable the plugin
Added `rank` field to my collection as a integer number
Added permissions to rank field in the settings
Populated the rank field manually with `0` and `1` on my 2 items
Attempting to sort on the collection page gives a console error: 
![image](https://github.com/plantagoIT/strapi-drag-drop-content-type-plugin/assets/23744606/598d8865-f660-47b6-9909-32a3e94214a9)

The sorting is not done on the app neither on the api. What did I miss? Or is this a bug?

**Comment by derschiw** [comment]
Did you run "npm run build" before?

**Comment by Hvesyr** [comment]
@derschiw Yes, and tried with `strapi develop` and `strapi start` and in neither worked.

**Comment by Hvesyr** [comment]
I figured out the problem, I had a `beforeUpdate` lifecycle on my collection interrupting the plugin. Everything is working now. Thanks.
