### ISSUE TITLE
Bug & Question: Drag and Drop dropdown title

### ISSUE THREAD

**Issue by Adam-AbJab** [plantagoIT/strapi-drag-drop-content-type-plugin#83]
hello,
1. Bug: leaving the "Title Field Name" empty so it takes the entryTitle not working well, it's taking the ID anyways.

![Screenshot 2024-06-05 at 11 45 24](https://github.com/plantagoIT/strapi-drag-drop-content-type-plugin/assets/89073692/fae2712c-1fbe-4bdb-b642-9257ae8be56e)
![Screenshot 2024-06-05 at 11 46 29](https://github.com/plantagoIT/strapi-drag-drop-content-type-plugin/assets/89073692/939f54fd-70cd-405a-81f9-ea835adfc358)
![Screenshot 2024-06-05 at 11 47 31](https://github.com/plantagoIT/strapi-drag-drop-content-type-plugin/assets/89073692/6635bb01-44b4-46b7-af8c-3caa9495fd36)

2. Question: the "Title Field Name" is generic for all the fields and that makes it harder when the content types have different field names that I want to sort according to it(that won't be a problem if 1 is working well:P).

**Comment by Brend4n** [comment]
This bug has been fixed but the package on NPM is not updated, so you'll need to install from this github repo.

**Comment by derschiw** [comment]
Oh crap sorry, npm is now in 1.5.3 too
